package server

var ImageTypes = map[string]bool {"jpg" : true, "jpeg" : true, "png": true}

var HeroMap = map[string]string {
"abaddon" : "abaddon",
"alchemist" : "alchemist",
"ancient apparition" : "ancient_apparition",
"anti mage" : "anti-mage",
"arc warden" : "arc_warden",
"axe" : "axe",
"bane" : "bane",
"batrider" : "batrider",
"beastmaster" : "beastmaster",
"bloodseeker" : "bloodseeker",
"bounty hunter" : "bounty_hunter",
"brewmaster" : "brewmaster",
"bristleback" : "bristleback",
"broodmother" : "broodmother",
"centaur warrunner" : "centaur_warrunner",
"chaos knight" : "chaos_knight",
"chen" : "chen",
"clinkz" : "clinkz",
"clockwerk" : "clockwerk",
"crystal maiden" : "crystal_maiden",
"dark seer" : "dark_seer",
"dazzle" : "dazzle",
"death prophet" : "death_prophet",
"disruptor" : "disruptor",
"doom" : "doom",
"dragon knight" : "dragon_knight",
"drow ranger" : "drow_ranger",
"earth spirit" : "earth_spirit",
"earthshaker" : "earthshaker",
"elder titan" : "elder_titan",
"ember spirit" : "ember_spirit",
"enchantress" : "enchantress",
"enigma" : "enigma",
"faceless void" : "faceless_void",
"gyrocopter" : "gyrocopter",
"huskar" : "huskar",
"invoker" : "invoker",
"io" : "io",
"jakiro" : "jakiro",
"juggernaut" : "juggernaut",
"keeper of the light" : "keeper_of_the_light",
"kunkka" : "kunkka",
"legion commander" : "legion_commander",
"leshrac" : "leshrac",
"lich" : "lich",
"lifestealer" : "lifestealer",
"lina" : "lina",
"lion" : "lion",
"lone druid" : "lone_druid",
"luna" : "luna",
"lycan" : "lycan",
"magnus" : "magnus",
"medusa" : "medusa",
"meepo" : "meepo",
"mirana" : "mirana",
"monkey king" : "monkey_king",
"morphling" : "morphling",
"naga siren" : "naga_siren",
"nature s prophet" : "natures_prophet",
"necrophos" : "necrophos",
"night stalker" : "night_stalker",
"nyx assassin" : "nyx_assassin",
"ogre magi" : "ogre_magi",
"omniknight" : "omniknight",
"oracle" : "oracle",
"outworld devourer" : "outworld_devourer",
"phantom assassin" : "phantom_assassin",
"phantom lancer" : "phantom_lancer",
"phoenix" : "phoenix",
"puck" : "puck",
"pudge" : "pudge",
"pugna" : "pugna",
"queen of pain" : "queen_of_pain",
"razor" : "razor",
"riki" : "riki",
"rubick" : "rubick",
"sand king" : "sand_king",
"shadow demon" : "shadow_demon",
"shadow fiend" : "shadow_fiend",
"shadow shaman" : "shadow_shaman",
"silencer" : "silencer",
"skywrath mage" : "skywrath_mage",
"slardar" : "slardar",
"slark" : "slark",
"sniper" : "sniper",
"spectre" : "spectre",
"spirit breaker" : "spirit_breaker",
"storm spirit" : "storm_spirit",
"sven" : "sven",
"techies" : "techies",
"templar assassin" : "templar_assassin",
"terrorblade" : "terrorblade",
"tidehunter" : "tidehunter",
"timbersaw" : "timbersaw",
"tinker" : "tinker",
"tiny" : "tiny",
"treant protector" : "treant_protector",
"troll warlord" : "troll_warlord",
"tusk" : "tusk",
"underlord" : "underlord",
"undying" : "undying",
"ursa" : "ursa",
"vengeful spirit" : "vengeful_spirit",
"venomancer" : "venomancer",
"viper" : "viper",
"visage" : "visage",
"warlock" : "warlock",
"weaver" : "weaver",
"windranger" : "windranger",
"winter wyvern" : "winter_wyvern",
"witch doctor" : "witch_doctor",
"wraith king" : "wraith_king",
"zeus" : "zeus",
}